name: motion_sensors
description: Local override of the motion_sensors plugin (v0.1.0) vendored for namespace fixes.
version: 0.1.0
homepage: https://github.com/sakebook/motion_sensors

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.sakebook.motion_sensors
        pluginClass: MotionSensorsPlugin
